development:
  adapter: postgresql
  encoding: unicode
  database: loon_development
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: loon_test
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000
